### ISSUE TITLE
Csv export

### ISSUE THREAD

**Issue by barocsi** [notpeter/crunchbase-data#3]
Hi, do you have, by any means access to fresh crunchbase csv export? I would purchase a 2017 fresh, one time dump if available.

**Comment by ghost** [comment]
Hey Barcosi,

I have a fresh copy (as of today). Is this for personal use or to publish?
Send me your email to npgpxebh@grr.la.

**Comment by barocsi** [comment]
Hi, did.

**Comment by EmJans** [comment]
Hi, 

I would like to get a copy for personal use. Is this still possible?

**Comment by aditya-malte** [comment]
Hi, is a fresh dump available? I'd like it for personal use. Thanks

**Comment by ghost** [comment]
hey! same issue) I really need this
