### ISSUE TITLE
CSV per 

### ISSUE THREAD

**Issue by raymundodiaz** [notpeter/crunchbase-data#4]
I want to do my undergraduate thesis doing an analysis of social networks of companies and entrepreneurs in Latin America and I am looking for an updated database. Will you have a recent export?

**Comment by notpeter** [comment]
Sorry man, this is all I've got.

They do have an [Academic Research Access](https://about.crunchbase.com/partners/academic-research-access/) program, probably worth contacting them (or tapping your networks to find someone at a university they partner with).

**Comment by raymundodiaz** [comment]
Thanks man! I'll try that way. :)
